spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unlaps20221ce15
    username: root
    password: root1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect