spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unlaps20221ce15
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernte.dialect.MySQL5Dialect
  thymeleaf:
    cache: false