spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unlaps20221ce15
    username: root
    password: lucamichel1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect